[workspace]
members = [ "hook", "injector", "converter", "common" ]
resolver = "2"

[profile.release]
strip = true
opt-level = 3
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false