# apparently certain perfectly standard code style preferences can only be enforced in nightly >_>
unstable_features = true

hard_tabs = true
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
fn_params_layout = "Compressed"
fn_single_line = true
format_code_in_doc_comments = true
hex_literal_case = "Upper"
imports_indent = "Visual"
imports_layout = "HorizontalVertical"
match_arm_blocks = false
match_block_trailing_comma = true
max_width = 200
imports_granularity = "Item"
newline_style = "Windows"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
reorder_imports = false
group_imports = "StdExternalCrate"
trailing_comma = "Never"
use_field_init_shorthand = true
use_try_shorthand = true
version = "Two"
where_single_line = true
wrap_comments = true